config/routes.rb
Crowdfunder::Application.routes.draw do
  resources :projects do
    resources :pledges, :only => [:new, :create]
  end

  namespace :my do
    resources :projects do
      resources :images
    end
  end
  resources :user_sessions
  root :to => 'static_page#index'
  resources :users, :except => [:index]

  get 'login' => "user_sessions#new", :as => :login
  delete 'logout'=> "user_sessions#destroy", :as => :logout

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :project
  attr_accessible :file

  mount_uploader :file, ImageUploader

  validates :project, :file, presence: true
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  attr_accessible :amount, :project, :user_id
  belongs_to :user
  belongs_to :project

  validates :amount, :project_id, :user_id, presence: true
  validates_numericality_of :amount, :only_integer => true,  :greater_than => 0
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
	has_many :pledges
  has_many :images, dependent: :destroy
  has_many :supporters, :through => :pledges, :source => :user
  
  attr_accessible :description, :goal, :teaser, :title, :user_id

  validates :title, presence: true, length: {maximum: 100}
  validates :teaser, presence: true, length: {maximum: 255}
  validates :description, presence: true
  validates :goal, presence: true, numericality: {greater_than: 0, allow_blank: true}

  def raised
    self.pledges.sum(:amount)
  end

  def percent_raised
    ((raised.to_f / goal) * 100).to_i
  end

  def succeeded?
    percent_raised >= 100
  end

  def surpassed_goal?
    percent_raised > 100
  end

  def number_of_supporters
    self.supporters.uniq.count # if you make two pledges, you are still one supporter
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation
  has_many :projects
  has_many :pledges

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates_confirmation_of :password, :message => "should match confirmation", :if => :password

  def name
    "#{first_name} #{last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :nav_state

  protected

  # Sorcery automatically looks for a method called not_authenticated  
  
  def not_authenticated
    redirect_to login_path, :alert => "Please login first."
  end

  def nav_state
  	
  end

end

app/controllers/my/images_controller.rb
class My::ImagesController < ApplicationController

  before_filter :require_login
  before_filter :require_project

  def index
    @images = @project.images.order(:id)
    @image  = @project.images.build
  end

  def create
    @image = @project.images.build params[:image]
    if @image.save
      redirect_to [:my, @project, :images], notice: "Image uploaded. Check it out below."
    else
      @images = @project.images.order(:id)
      render :index
    end
  end

  protected

  def require_project
    @project = current_user.projects.find params[:project_id]
  end

  def nav_state
    @nav = :my_projects
  end
end

app/controllers/my/projects_controller.rb
class My::ProjectsController < ApplicationController

  before_filter :require_login
  before_filter :require_project, except: [:index, :new, :create]

  def index
    @projects = current_user.projects.order('projects.created_at DESC').all
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def update
    if @project.update_attributes params[:project]
      redirect_to [:my, :projects], notice: "Project updated!"
    else
      render :edit
    end
  end

  def create
    @project = current_user.projects.build params[:project]
    if @project.save
      redirect_to [:my, :projects], notice: "Project created!"
    else
      render :new
    end
  end

  def nav_state
    @nav = :my_projects
  end

  protected
  def require_project
    @project = current_user.projects.find params[:id]
  end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  before_filter :require_login
  before_filter :require_project

  def new
    @pledge = @project.pledges.build
  end

  def create
    @pledge = @project.pledges.build(params[:pledge])
    @pledge.user = current_user

    if @pledge.save
      UserMailer.new_pledge(@pledge).deliver
      redirect_to @project, notice: "Nice! Thanks for pledging $#{@pledge.amount} for this project."
    else
      render :new
    end
  
  end

  protected

  def require_project
    @project = Project.find params[:project_id]
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects=Project.all
    @projects = Project.order('projects.created_at DESC').page(params[:page])

  end

  def show
    @project=Project.find(params[:id])
  end

  def new
    @project=Project.new
  end

  def nav_state
    @nav = :projects
  end
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to my_projects_path, :notice => "deleted"
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
	def index

	end

	def nav_state
		@nav = :home
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      if @user = login(params[:email],params[:password],params[:remember])
        format.html { redirect_back_or_to(:root, :notice => 'Login successful!') }

      else
        format.html { flash.now[:alert] = "Login failed"; render :action => "new" }
        # format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    logout
    redirect_to(:root, :notice => "Bye")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
	 	@user = User.new
	end

	def create
		@user = User.new(params[:user])
    
    if @user.save
      auto_login(@user)
      flash[:notice] = "Account created"
      redirect_to root_path
    else
      render :new
    end
	end

	def show
		@user = User.find(params[:id])
	end
end




# def redirect_to_back_or_default(default = root_path)
#   if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
#     redirect_to :back
#   else
#     redirect_to default
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my/images_helper.rb
module My::ImagesHelper
end

app/helpers/my/projects_helper.rb
module My::ProjectsHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/shared/nav' %>

<div class="flashes">

  <% flash.each do |name,msg| %>
  <%= "#{msg}" %>
<% end %>
</div>


<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/shared/_nav.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div id="container">
      <a class="brand" href="#">CrowdFunder</a>
      <div class="nav-collapse collapse">
        <ul class="nav">

            <li class="<%= 'active' if @nav == :home %>">
              <%= link_to 'Home', :root %>
            </li>
            <li class="<%= 'active' if @nav == :projects %>">
              <%= link_to 'Projects', :projects %>
            </li>
            <% if logged_in? %>
              <li class="divider-vertical"></li>
              <li class="<%= 'active' if @nav == :my_projects %>">
                <%= link_to 'My Projects', [:my, :projects] %>
                <li>
                  <%= link_to "New Project", new_my_project_path %>
                </li>
              <li>
              


            <% end %>

          
          <li>
            <% if current_user %>
                <%= link_to "Logout", logout_path, method: :delete%>
            <% else %>
              <%= link_to 'Login', login_path %> 
            <% end %>
          </li>
          
          <% unless current_user %>
          <li style=""><%= link_to 'Sign Up', :new_user %></li>
          <% end %>


        </ul>
      </div>
      </div>
    </div>
  </div>

app/views/my/images/_image.html.erb
<%= form_for([:my, @project, @image]) do |f| %>

  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.file_field :file %>
	<%= f.submit "Upload Image" %>
<% end %>

<% @images.each do |i| %>
	<div class = "image"> 
		<img src= "<%= i.file %>" />		
	</div>
<% end %>

app/views/my/images/index.html.erb
<%= render "image" %>

app/views/my/projects/edit.html.erb
<%= form_for ([:my, @project]) do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  
  <%= f.label "Teaser" %>
  <%= f.text_field :teaser %>

  <%= f.label "Description" %>
  <%= f.text_area :description %>

  <%= f.label "Goal" %>
  <%= f.number_field :goal %>


	<%= f.submit "Update Project" %>
<% end %>

<%= link_to "Manage Images", my_project_images_path(@project) %> | 
<%= link_to 'Delete Project', project_path(@project), :confirm => 'Are you sure you want to delete this product?', :method => :delete %>

app/views/my/projects/index.html.erb
<% @projects.each do |pro| %>
	<div class="project">
		<h2><%= pro.title %></h2>
    <%= pro.teaser %>
    <%= pro.description %>
    <% pro.images.each do |i| %>
      <div class = "image"> 
      <img src= "<%= i.file %>" width="200px" />    
      </div>
    <% end %>
    <%= link_to "Edit", edit_my_project_path(pro) %>
	</div>
<% end %>

app/views/my/projects/new.html.erb
<%= form_for ([:my, @project]) do |f| %>
  <%= f.label "Title" %>
  <%= f.text_field :title %>
  
  <%= f.label "Teaser" %>
  <%= f.text_field :teaser %>

  <%= f.label "Description" %>
  <%= f.text_area :description %>

  <%= f.label "Goal" %>
  <%= f.number_field :goal %>


  <%= f.submit "Publish Project" %>
<% end %>

app/views/pledges/_form.html.erb
<%= form_for ([@project, @project.pledges.build]) do |f| %>
  <%= f.label "Pledge Amount" %>
  <%= f.number_field :amount %>
  <%= f.submit "Pledge Now" %>
<% end %>

app/views/projects/_project.html.erb
<li class="project">
  <%= link_to project.title, project %>
  <br />
  <p>
    <%= project.teaser %>
  </p>
</li>

app/views/projects/_showproject.html.erb
<li class="project">
  <%= link_to project.title, project %>
  <br />
  <p>
    <%= project.teaser %>
  </p>
</li>

app/views/projects/index.html.erb
<h1>Projects Index Page</h1>

<div class="projects">
<h2> Listing projects </h2>
<% @projects.each do |proj| %>
<%= render "showproject", :project => proj %>
<% end %>
</div>
<%= paginate @projects %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<%= link_to "Back This Project", new_project_pledge_path(@project) %>

app/views/static_page/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <div class="hero-unit well">
        <h1>
          Crowd Funder
        </h1>
        <p>
          Sleek, intuitive, and powerful crowd-fund framework for faster and easier business ideas.
        </p>
        <p>
          <small>By:</small>
        </p>
        <div class="view"></div>
          <ul class="breadcrumb">
            <li>
              <a href="https://github.com/estiens/" onclick="_gaq.push(['_trackEvent', 'Jumbotron actions', 'Jumbotron links', 'GitHub project']);">Eric</a> - 
            </li>
            
            <li>
              <a href="https://github.com/ahmednadar" onclick="_gaq.push(['_trackEvent', 'Jumbotron actions', 'Jumbotron links', 'GitHub project']);">Ahmed</a> - 
            </li>

            <li>
              <a href="https://github.com/beccacoady" onclick="_gaq.push(['_trackEvent', 'Jumbotron actions', 'Jumbotron links', 'GitHub project']);">Rebecca</a>
            </li>      
          </ul>

      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span4">
      <h4>
        The Warden and the Wolf King
      </h4>
      <small>by Andrew Peterson</small>
      <p>
        Rabbit Room Press presents the long-awaited final volume of the Christy Award-winning Wingfeather Saga
      </p>
      <p>
        <a class="btn" href="#">View details »</a>
      </p>
    </div>
    <div class="span4">
      <h4>
        Reaper Miniatures Bones II: The Return Of Mr Bones!
      </h4>
      <small>by Reaper Miniatures</small>
      <p>
        Reaper Miniatures Bones II is a project to continue the expansion of Reaper's Bones line of high-quality plastic gaming miniatures.
      </p>
      <p>
        <a class="btn" href="#">View details »</a>
      </p>
    </div>
    <div class="span4">
      <h4>
        Completely Royal - Elite Belts
      </h4>
      <small>Completely Royal - Elite Belts</small>
      <p>
        What started out of necessity has turned into a passion. Completely Royal, amazing belts, unbelievable fit.
      </p>
      <p>
        <a class="btn" href="#">View details »</a>
      </p>
    </div>
  </div>
</div>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
  <div>
  	<%= label_tag "keep me logged in" %><br />
    <%= check_box_tag :remember %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>New User</h1>
	
<%= form_for(@user) do |f|%>
	<%= f.label "First Name"%>
	<%= f.text_field :first_name %>
	<%= f.label "Last Name" %>
	<%= f.text_field :last_name %>
	<%= f.label "Email" %>
	<%= f.email_field :email %>
	<%= f.label "Password"%>
	<%= f.password_field :password %>
	<%= f.label "Password Confirmation"%>
	<%= f.password_field :password_confirmation %>
	<%= f.submit "Create Account" %>

	<% unless f.object.errors.empty? %>
	<div class="alert alert-error">
		<strong>Try again after finxig the following steps:</strong><br>
		<ul>
			<% f.object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<% end %>

app/views/users/show.html.erb
<h2>Show User</h2>